In [1]:
import torch

x = torch.tensor([5,3])
y = torch.tensor([2,1])

print(x*y)

tensor([10,  3])


In [3]:
z = torch.rand([2,5])
z

tensor([[0.3542, 0.5986, 0.9556, 0.3166, 0.7333],
        [0.0494, 0.8653, 0.7983, 0.0362, 0.0212]])

In [4]:
z.view([1,10])

tensor([[0.3542, 0.5986, 0.9556, 0.3166, 0.7333, 0.0494, 0.8653, 0.7983, 0.0362,
         0.0212]])

In [6]:
import torch
import torchvision
from torchvision import transforms, datasets

In [ ]:
train = datasets.MNIST('', train=True, download=True, transform=) 

test = 