In [1]:
import numpy as np

In [2]:
import torch

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
arr = np.array(mylist)

In [8]:
arr

array([1, 2, 3])

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix.shape

(3, 3)

In [12]:
mynewmatrix = np.array(mylist)

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5)) * 100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [16]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(5,5)

array([[0.35158754, 0.64702036, 0.57907856, 0.68774184, 0.9386205 ],
       [0.03156353, 0.65894999, 0.09217368, 0.92855521, 0.74920982],
       [0.52878694, 0.61038187, 0.56969497, 0.70283685, 0.04336947],
       [0.96986574, 0.63865453, 0.01763825, 0.84378665, 0.19013367],
       [0.27478632, 0.65573399, 0.50400727, 0.591116  , 0.94405606]])

In [19]:
np.random.randn(10)

array([-0.48306608,  1.66360981,  0.44636438,  1.23682896,  1.00853583,
        1.28689228, -0.94564086,  0.21277751, -1.42627168,  0.45569088])

In [20]:
np.random.normal(10)

10.374752881589558

In [21]:
np.random.randint(1, 100, 10)

array([23, 23, 70, 53, 89, 56,  4, 26, 59, 97])

In [22]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [27]:
arr.shape

(25,)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

48

In [30]:
ranarr.min()

10

In [31]:
ranarr.argmax()

1

In [32]:
arr.dtype

dtype('int32')

In [36]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. ])

In [39]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
slice_of_arr = arr[0:6]

In [47]:
slice_of_arr[:] = 99

In [49]:
arr_copy = arr.copy()

In [51]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
arr_2d[2,2]

45

In [61]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr[arr < 6]

array([1, 2, 3, 4, 5])

In [71]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr / arr

C:\Anaconda3\envs\DLND\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
1/arr

C:\Anaconda3\envs\DLND\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [74]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [76]:
arr.sum()

45

In [77]:
arr.mean()

4.5

In [78]:
arr.max()

9

In [79]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])

In [83]:
arr_2d.sum(axis = 1)

array([10, 26, 42])