In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.4.0'

In [3]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [8]:
x = torch.from_numpy(arr)

In [9]:
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [10]:
type(x)

torch.Tensor

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [14]:
torch.int32

torch.int32

In [17]:
arr2d = np.arange(0.0,12.0)

In [19]:
arr2d.reshape(4,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [22]:
x2 = torch.from_numpy(arr2d)

In [24]:
x2

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [27]:
arr[0] = 99

In [28]:
arr

array([99,  2,  3,  4,  5])

In [29]:
my_arr = np.arange(0,10)

In [30]:
my_tensor = torch.tensor(my_arr)

In [31]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)